#!/usr/bin/env bash

set -euo pipefail

# Bundle the current local OpenClaw build together with a minimal runtime
# profile so the target Mac installs THIS repository version instead of
# upstream openclaw@latest.

OPENCLAW_HOME="${OPENCLAW_HOME:-$HOME/.openclaw}"
# Runtime JSON profile files bundled into the archive (override for your machine).
OPENCLAW_MAC_PROFILE_SOURCE="${OPENCLAW_MAC_PROFILE_SOURCE:-/Users/lidongdong/Desktop/openclaw}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ARTIFACTS_ROOT="${OPENCLAW_MAC_BUNDLE_OUTPUT_DIR:-${REPO_ROOT}/.artifacts/openclaw-mac-bundles}"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
OUT_BASENAME="openclaw-mac-bundle-${TIMESTAMP}"
OUT_DIR="${ARTIFACTS_ROOT}/${OUT_BASENAME}"
OUT_TAR="${ARTIFACTS_ROOT}/${OUT_BASENAME}.tar.gz"
PACKAGE_DIR="${OUT_DIR}/packages"
LOCAL_PACKAGE_TGZ=""
LOCAL_PACKAGE_PATH=""
BUNDLE_ENV_PATH="${OUT_DIR}/.openclaw/.env"
SOURCE_HOME_FOR_REWRITE="${HOME}"
SOURCE_OPENCLAW_HOME="${OPENCLAW_HOME}"

echo "Packing OpenClaw runtime profile from: ${OPENCLAW_HOME}"
echo "Bundling config JSON from: ${OPENCLAW_MAC_PROFILE_SOURCE}"
echo "Using local repository: ${REPO_ROOT}"
echo "Writing bundle artifacts to: ${ARTIFACTS_ROOT}"

mkdir -p "${ARTIFACTS_ROOT}"
mkdir -p "${OUT_DIR}/.openclaw"
mkdir -p "${PACKAGE_DIR}"

copy_if_exists() {
  local src="$1"
  local dst="$2"
  if [ -f "${src}" ]; then
    mkdir -p "$(dirname "${dst}")"
    cp "${src}" "${dst}"
    echo "  [profile] ${src} -> ${dst}"
  else
    echo "  [profile] skipped missing file: ${src}"
  fi
}

# Match scripts/openclaw-prepack.ts: prepack skips rebuild when OPENCLAW_PREPACK_PREPARED is set
# only if these artifacts exist.
openclaw_dist_looks_ready() {
  local root="$1"
  if [ ! -f "${root}/dist/control-ui/index.html" ]; then
    return 1
  fi
  if [ ! -f "${root}/dist/index.js" ] && [ ! -f "${root}/dist/index.mjs" ]; then
    return 1
  fi
  shopt -s nullglob
  local assets=( "${root}/dist/control-ui/assets/"* )
  shopt -u nullglob
  local p
  for p in "${assets[@]}"; do
    if [ -f "${p}" ]; then
      return 0
    fi
  done
  return 1
}

dotenv_quote() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//$'\n'/\\n}"
  printf '"%s"' "${value}"
}

read_existing_bridge_token() {
  local source_env="$1"
  [ -f "${source_env}" ] || return 1

  python3 - "${source_env}" <<'PY'
import pathlib
import re
import sys

path = pathlib.Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
matches = re.findall(r'^[ \t]*OPENCLAW_BRIDGE_TOKEN[ \t]*=[ \t]*(.+)[ \t]*$', text, re.MULTILINE)
if not matches:
    raise SystemExit(1)
value = matches[-1].strip()
if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
    value = value[1:-1]
print(value)
PY
}

read_existing_env_value() {
  local source_env="$1"
  local key="$2"
  [ -f "${source_env}" ] || return 1

  python3 - "${source_env}" "${key}" <<'PY'
import pathlib
import re
import sys

path = pathlib.Path(sys.argv[1])
key = sys.argv[2]
text = path.read_text(encoding="utf-8")
matches = re.findall(rf'^[ \t]*{re.escape(key)}[ \t]*=[ \t]*(.+)[ \t]*$', text, re.MULTILINE)
if not matches:
    raise SystemExit(1)
value = matches[-1].strip()
if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
    value = value[1:-1]
print(value)
PY
}

create_bundle_env() {
  local dst="$1"
  local source_env="${OPENCLAW_HOME}/.env"
  local generated_bridge_token="${OPENCLAW_BRIDGE_TOKEN:-}"
  local agent_bot_api_base_url="${AGENT_BOT_API_BASE_URL:-}"
  local control_plane_base_url="${CONTROL_PLANE_BASE_URL:-}"
  local agent_bot_base_url="${AGENT_BOT_BASE_URL:-}"

  if [ -z "${generated_bridge_token}" ]; then
    generated_bridge_token="$(read_existing_bridge_token "${source_env}" 2>/dev/null || true)"
  fi
  if [ -z "${generated_bridge_token}" ]; then
    generated_bridge_token="change-me"
  fi
  if [ -z "${agent_bot_api_base_url}" ]; then
    agent_bot_api_base_url="$(read_existing_env_value "${source_env}" "AGENT_BOT_API_BASE_URL" 2>/dev/null || true)"
  fi
  if [ -z "${control_plane_base_url}" ]; then
    control_plane_base_url="$(read_existing_env_value "${source_env}" "CONTROL_PLANE_BASE_URL" 2>/dev/null || true)"
  fi
  if [ -z "${agent_bot_base_url}" ]; then
    agent_bot_base_url="$(read_existing_env_value "${source_env}" "AGENT_BOT_BASE_URL" 2>/dev/null || true)"
  fi

  cat > "${dst}" <<EOF
# Generated by scripts/package-openclaw-mac.sh
OPENCLAW_BRIDGE_TOKEN=$(dotenv_quote "${generated_bridge_token}")
EOF
  echo "  [profile] generated minimal env: ${dst}"

  cat >> "${dst}" <<'EOF'
OPENCLAW_CONTROL_PLANE_STATE_FILE="__OPENCLAW_HOME__/control-plane-state.json"
EOF

  if [ -n "${agent_bot_api_base_url}" ]; then
    cat >> "${dst}" <<EOF
AGENT_BOT_API_BASE_URL=$(dotenv_quote "${agent_bot_api_base_url}")
EOF
  fi
  if [ -n "${control_plane_base_url}" ]; then
    cat >> "${dst}" <<EOF
CONTROL_PLANE_BASE_URL=$(dotenv_quote "${control_plane_base_url}")
EOF
  fi
  if [ -n "${agent_bot_base_url}" ]; then
    cat >> "${dst}" <<EOF
AGENT_BOT_BASE_URL=$(dotenv_quote "${agent_bot_base_url}")
EOF
  fi
}

echo
echo "Building and packing local OpenClaw package..."
pushd "${REPO_ROOT}" >/dev/null

# Fast path: if dist/ is already complete, prepack only verifies (no pnpm build / ui:build).
# Slow path: force full prepack with OPENCLAW_MAC_PACK_FORCE_PREPACK_BUILD=1
#   (or any incomplete dist — we run build here, then pack with skip so prepack does not rebuild twice).
force_prepack="${OPENCLAW_MAC_PACK_FORCE_PREPACK_BUILD:-}"
if [ "${force_prepack}" = "1" ] || [ "${force_prepack}" = "true" ]; then
  echo "  [pack] OPENCLAW_MAC_PACK_FORCE_PREPACK_BUILD: prepack will run full build + ui:build (slow)."
  unset OPENCLAW_PREPACK_PREPARED
elif openclaw_dist_looks_ready "${REPO_ROOT}"; then
  echo "  [pack] dist/ looks ready — OPENCLAW_PREPACK_PREPARED=1 (prepack verifies only, no rebuild)."
  export OPENCLAW_PREPACK_PREPARED=1
else
  echo "  [pack] dist/ missing or incomplete — running pnpm build && pnpm ui:build..."
  pnpm build
  pnpm ui:build
  echo "  [pack] OPENCLAW_PREPACK_PREPARED=1 for pack (prepack verifies only)."
  export OPENCLAW_PREPACK_PREPARED=1
fi

# Prepack is fast when OPENCLAW_PREPACK_PREPARED=1; pnpm pack still walks and gzip-compresses
# everything in package.json "files" (dist/, docs/, skills/, assets/, …). That step alone often
# takes several minutes on a large tree — not stuck, just I/O + compression.
echo "  [pack] Creating npm tarball (dist + docs + skills + …) — this can take a few minutes…"

LOCAL_PACKAGE_TGZ="$(pnpm pack --pack-destination "${PACKAGE_DIR}" | tail -n 1 | tr -d '\r')"
popd >/dev/null

if [ -z "${LOCAL_PACKAGE_TGZ}" ]; then
  echo "Failed to produce local OpenClaw tarball" >&2
  exit 1
fi

if [[ "${LOCAL_PACKAGE_TGZ}" = /* ]]; then
  LOCAL_PACKAGE_PATH="${LOCAL_PACKAGE_TGZ}"
  LOCAL_PACKAGE_TGZ="$(basename "${LOCAL_PACKAGE_PATH}")"
else
  LOCAL_PACKAGE_PATH="${PACKAGE_DIR}/${LOCAL_PACKAGE_TGZ}"
fi

if [ ! -f "${LOCAL_PACKAGE_PATH}" ]; then
  echo "Failed to produce local OpenClaw tarball" >&2
  exit 1
fi

echo "  [package] ${LOCAL_PACKAGE_PATH}"

copy_if_exists "${OPENCLAW_MAC_PROFILE_SOURCE}/openclaw.json" "${OUT_DIR}/.openclaw/openclaw.json"
copy_if_exists "${OPENCLAW_MAC_PROFILE_SOURCE}/exec-approvals.json" "${OUT_DIR}/.openclaw/exec-approvals.json"
copy_if_exists "${OPENCLAW_HOME}/workspace/SOUL.md" "${OUT_DIR}/.openclaw/workspace/SOUL.md"
create_bundle_env "${BUNDLE_ENV_PATH}"

cat > "${OUT_DIR}/README-import.md" <<EOF
OpenClaw macOS runtime bundle
=============================

This bundle contains:

- packages/${LOCAL_PACKAGE_TGZ}
- .openclaw/.env
- .openclaw/openclaw.json
- .openclaw/exec-approvals.json
- .openclaw/workspace/SOUL.md

Important:

- Install the packaged local OpenClaw tarball from this bundle.
- Do NOT use \`npm install -g openclaw@latest\` on the target Mac, because the
  upstream package does not include the control-plane compatibility layer used
  by agent-bot-task-a.
- Preserve the target Mac's existing \`~/.openclaw/control-plane-state.json\`
  during upgrades. That file stores the remote-agent-to-local-agent sync mapping.
  If it gets overwritten, portal chat may report
  \`REMOTE_AGENT_NOT_FOUND: remote agent is not synced to a local OpenClaw agent\`
  even when the old workspace files still exist.

To import on a target Mac:

1. Ensure Node.js (22.16+ or 24.x) is installed.

2. Extract this archive in your home directory:

   cd ~
   tar -xzf /path/to/${OUT_TAR}

3. Run the bundled installer:

   bash ~/${OUT_BASENAME}/install-local-openclaw.sh

4. What the installer does:

   - installs THIS local OpenClaw build globally
   - prompts before overwriting existing ~/.openclaw/.env, ~/.openclaw/openclaw.json, and ~/.openclaw/exec-approvals.json
   - when replacing ~/.openclaw/.env, substitutes \$HOME/.openclaw in place of __OPENCLAW_HOME__
   - when replacing ~/.openclaw/openclaw.json, preserves the target Mac's existing agents.list
   - when replacing ~/.openclaw/openclaw.json, rewrites source-machine /Users/... paths to the target \$HOME
   - copies SOUL.md
   - preserves the target Mac's existing ~/.openclaw/control-plane-state.json

5. Choose how you want to run the Gateway:

   Foreground (one-shot terminal run):

   export OPENCLAW_BRIDGE_TOKEN=change-me
   export OPENCLAW_CONTROL_PLANE_STATE_FILE="\$HOME/.openclaw/control-plane-state.json"
   openclaw gateway run --config ~/.openclaw/openclaw.json

   launchd service (so \`openclaw gateway start\` works later):

   # ~/.openclaw/.env has already been restored above; edit it if needed.
   openclaw gateway install
   openclaw gateway status --deep

6. Verify the compatibility routes:

   curl -i http://127.0.0.1:15661/__control-plane/runtime-context \\
     -H "x-openclaw-bridge-token: \$OPENCLAW_BRIDGE_TOKEN"

   curl -i -X POST http://127.0.0.1:15661/__control-plane/bootstrap \\
     -H "content-type: application/json" \\
     -H "x-openclaw-bridge-token: \$OPENCLAW_BRIDGE_TOKEN" \\
     -d '{}'

   curl -i -X POST http://127.0.0.1:15661/__control-plane/skills/snapshot/apply \\
     -H "content-type: application/json" \\
     -H "x-openclaw-bridge-token: \$OPENCLAW_BRIDGE_TOKEN" \\
     -d '{"snapshotId":"debug","packages":[]}'

Expected:

- runtime-context returns 200
- bootstrap no longer returns 404
- skills/snapshot/apply no longer returns 404
EOF

cat > "${OUT_DIR}/install-local-openclaw.sh" <<EOF
#!/usr/bin/env bash

set -euo pipefail

BUNDLE_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
PACKAGE_NAME="${LOCAL_PACKAGE_TGZ}"

prompt_overwrite_file() {
  local target_path="\$1"
  local label="\$2"
  if [ ! -e "\${target_path}" ]; then
    return 0
  fi
  if [ ! -t 0 ]; then
    echo "Preserving existing \${label} (non-interactive install)." >&2
    return 1
  fi
  while true; do
    printf 'Overwrite existing %s? [y/N] ' "\${label}" >&2
    IFS= read -r reply || return 1
    case "\${reply}" in
      [Yy]|[Yy][Ee][Ss])
        return 0
        ;;
      ""|[Nn]|[Nn][Oo])
        echo "Preserving existing \${label}." >&2
        return 1
        ;;
      *)
        echo "Please answer y or n." >&2
        ;;
    esac
  done
}

mkdir -p "\$HOME/.openclaw/workspace"
npm install -g "\${BUNDLE_DIR}/packages/\${PACKAGE_NAME}"

GLOBAL_NPM_ROOT="\$(npm root -g)"
INSTALLED_OPENCLAW_ROOT="\${GLOBAL_NPM_ROOT}/openclaw"
python3 - "\${BUNDLE_DIR}/packages/\${PACKAGE_NAME}" "\${INSTALLED_OPENCLAW_ROOT}" <<'PY'
import json
import pathlib
import shutil
import sys
import tarfile
import tempfile

bundle_tgz = pathlib.Path(sys.argv[1])
installed_root = pathlib.Path(sys.argv[2])

def collect_runtime_closure(node_modules_dir, dependency_specs):
    package_cache = {}
    closure = set()
    queue = list(dependency_specs.keys())

    while queue:
        dep_name = queue.pop(0)
        if dep_name in closure:
            continue
        dep_package_json = node_modules_dir.joinpath(*dep_name.split("/"), "package.json")
        if not dep_package_json.exists():
            return None
        package_json = package_cache.get(dep_name)
        if package_json is None:
            package_json = json.loads(dep_package_json.read_text(encoding="utf-8"))
            package_cache[dep_name] = package_json
        closure.add(dep_name)
        for child_name in {
            **package_json.get("dependencies", {}),
            **package_json.get("optionalDependencies", {}),
        }:
            if child_name not in closure:
                queue.append(child_name)

    return sorted(closure)

with tempfile.TemporaryDirectory(prefix="openclaw-runtime-bundle-") as tmp_dir:
    with tarfile.open(bundle_tgz, "r:gz") as archive:
        archive.extractall(tmp_dir)

    packaged_root = pathlib.Path(tmp_dir) / "package"
    packaged_extensions_root = packaged_root / "dist" / "extensions"
    installed_node_modules = installed_root / "node_modules"

    if packaged_extensions_root.exists():
        for plugin_dir in sorted(packaged_extensions_root.iterdir()):
            if not plugin_dir.is_dir():
                continue
            manifest_path = plugin_dir / "package.json"
            staged_node_modules = plugin_dir / "node_modules"
            if not manifest_path.exists() or not staged_node_modules.exists():
                continue

            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            if manifest.get("openclaw", {}).get("bundle", {}).get("stageRuntimeDependencies") is not True:
                continue

            runtime_deps = {
                **manifest.get("dependencies", {}),
                **manifest.get("optionalDependencies", {}),
            }
            if not runtime_deps:
                continue

            dependency_names = collect_runtime_closure(staged_node_modules, runtime_deps)
            if dependency_names is None:
                continue

            for dep_name in dependency_names:
                target_package_json = installed_node_modules.joinpath(*dep_name.split("/"), "package.json")
                if target_package_json.exists():
                    continue
                source_path = staged_node_modules.joinpath(*dep_name.split("/"))
                if not source_path.exists():
                    continue
                target_path = installed_node_modules.joinpath(*dep_name.split("/"))
                target_path.parent.mkdir(parents=True, exist_ok=True)
                shutil.copytree(source_path, target_path, dirs_exist_ok=True)
PY
if [ -f "\${INSTALLED_OPENCLAW_ROOT}/scripts/postinstall-bundled-plugins.mjs" ]; then
  node "\${INSTALLED_OPENCLAW_ROOT}/scripts/postinstall-bundled-plugins.mjs"
fi
python3 - "\${INSTALLED_OPENCLAW_ROOT}" <<'PY'
import json
import pathlib
import sys

package_root = pathlib.Path(sys.argv[1])
extensions_root = package_root / "dist" / "extensions"
root_node_modules = package_root / "node_modules"
missing = []

if extensions_root.exists():
    for plugin_dir in sorted(extensions_root.iterdir()):
        if not plugin_dir.is_dir():
            continue
        manifest_path = plugin_dir / "package.json"
        if not manifest_path.exists():
            continue
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except Exception:
            continue
        if manifest.get("openclaw", {}).get("bundle", {}).get("stageRuntimeDependencies") is not True:
            continue
        runtime_deps = {
            **manifest.get("dependencies", {}),
            **manifest.get("optionalDependencies", {}),
        }
        for dep_name in sorted(runtime_deps):
            dep_path = root_node_modules.joinpath(*dep_name.split("/"), "package.json")
            if not dep_path.exists():
                missing.append(f"{plugin_dir.name}:{dep_name}")

if missing:
    raise SystemExit(
        "Bundled plugin runtime dependencies are still missing after install: " + ", ".join(missing)
    )
PY

if [ -f "\${BUNDLE_DIR}/.openclaw/openclaw.json" ] && prompt_overwrite_file "\$HOME/.openclaw/openclaw.json" "~/.openclaw/openclaw.json"; then
  python3 - "\${BUNDLE_DIR}/.openclaw/openclaw.json" "\$HOME/.openclaw/openclaw.json" "\$HOME" "${SOURCE_OPENCLAW_HOME}" "${SOURCE_HOME_FOR_REWRITE}" <<'PY'
import json
import pathlib
import sys

bundle_path = pathlib.Path(sys.argv[1])
target_path = pathlib.Path(sys.argv[2])
target_home = sys.argv[3]
source_openclaw_home = sys.argv[4]
source_home = sys.argv[5]
target_openclaw_home = str(pathlib.Path(target_home) / ".openclaw")

def rewrite_value(value):
    if isinstance(value, str):
        out = value
        if source_openclaw_home:
            out = out.replace(source_openclaw_home, target_openclaw_home)
        if source_home:
            out = out.replace(source_home, target_home)
        return out
    if isinstance(value, list):
        return [rewrite_value(item) for item in value]
    if isinstance(value, dict):
        return {key: rewrite_value(item) for key, item in value.items()}
    return value

bundle = json.loads(bundle_path.read_text(encoding="utf-8"))
bundle = rewrite_value(bundle)

if target_path.exists():
    try:
        existing = json.loads(target_path.read_text(encoding="utf-8"))
    except Exception:
        existing = None
    if isinstance(existing, dict):
        existing_agents = existing.get("agents")
        existing_list = existing_agents.get("list") if isinstance(existing_agents, dict) else None
        if isinstance(existing_list, list):
            bundle_agents = bundle.get("agents")
            if not isinstance(bundle_agents, dict):
                bundle_agents = {}
                bundle["agents"] = bundle_agents
            bundle_agents["list"] = existing_list

target_path.write_text(
    json.dumps(bundle, ensure_ascii=False, indent=2) + "\n",
    encoding="utf-8",
)
PY
fi
if [ -f "\${BUNDLE_DIR}/.openclaw/exec-approvals.json" ] && prompt_overwrite_file "\$HOME/.openclaw/exec-approvals.json" "~/.openclaw/exec-approvals.json"; then
  cp "\${BUNDLE_DIR}/.openclaw/exec-approvals.json" "\$HOME/.openclaw/exec-approvals.json"
fi
if [ -f "\${BUNDLE_DIR}/.openclaw/control-plane-state.json" ]; then
  echo "Preserving existing \$HOME/.openclaw/control-plane-state.json; bundled control-plane-state.json is ignored."
fi
if [ -f "\${BUNDLE_DIR}/.openclaw/workspace/SOUL.md" ]; then
  mkdir -p "\$HOME/.openclaw/workspace"
  cp "\${BUNDLE_DIR}/.openclaw/workspace/SOUL.md" "\$HOME/.openclaw/workspace/SOUL.md"
fi
if [ -f "\${BUNDLE_DIR}/.openclaw/.env" ] && prompt_overwrite_file "\$HOME/.openclaw/.env" "~/.openclaw/.env"; then
  BUNDLE_ENV_CONTENT="\$(<"\${BUNDLE_DIR}/.openclaw/.env")"
  BUNDLE_ENV_CONTENT="\${BUNDLE_ENV_CONTENT//__OPENCLAW_HOME__/\$HOME/.openclaw}"
  EXISTING_ENV_PATH="\$HOME/.openclaw/.env"
  TMP_ENV_PATH="\$HOME/.openclaw/.env.tmp.\$\$"
  printf '%s\n' "\${BUNDLE_ENV_CONTENT}" > "\${TMP_ENV_PATH}"
  python3 - "\${TMP_ENV_PATH}" "\${EXISTING_ENV_PATH}" <<'PY'
import pathlib
import re
import sys

bundle_path = pathlib.Path(sys.argv[1])
existing_path = pathlib.Path(sys.argv[2])
preserve_keys = [
    "AGENT_BOT_API_BASE_URL",
    "CONTROL_PLANE_BASE_URL",
    "AGENT_BOT_BASE_URL",
]

def parse_env(path):
    result = {}
    if not path.exists():
        return result
    text = path.read_text(encoding="utf-8")
    for key in preserve_keys:
        matches = re.findall(rf'^[ \t]*{re.escape(key)}[ \t]*=[ \t]*(.+)[ \t]*$', text, re.MULTILINE)
        if matches:
            result[key] = matches[-1].strip()
    return result

bundle_text = bundle_path.read_text(encoding="utf-8")
existing = parse_env(existing_path)
bundle = parse_env(bundle_path)

merged_lines = bundle_text.splitlines()
for key in preserve_keys:
    value = bundle.get(key) or existing.get(key)
    if value:
        merged_lines = [
            line for line in merged_lines
            if not re.match(rf'^[ \t]*{re.escape(key)}[ \t]*=', line)
        ]
        merged_lines.append(f"{key}={value}")

bundle_path.write_text("\n".join(merged_lines).rstrip("\n") + "\n", encoding="utf-8")
PY
  mv "\${TMP_ENV_PATH}" "\${EXISTING_ENV_PATH}"
fi

echo "Installed local OpenClaw package: \${PACKAGE_NAME}"
echo "Merged ~/.openclaw/openclaw.json:"
echo "  - preserved target machine agents.list"
echo "  - rewrote source-machine home paths to \$HOME"
echo "Next:"
echo "  Foreground run:"
echo "    export OPENCLAW_BRIDGE_TOKEN=<same token as control plane>"
echo "    export OPENCLAW_CONTROL_PLANE_STATE_FILE=\$HOME/.openclaw/control-plane-state.json"
echo "    openclaw gateway run --config ~/.openclaw/openclaw.json"
echo "  launchd service:"
echo "    # .env was restored to \$HOME/.openclaw/.env"
echo "    openclaw gateway install"
echo "    openclaw gateway status --deep"
EOF

chmod +x "${OUT_DIR}/install-local-openclaw.sh"

echo "Creating archive: ${OUT_TAR}"
tar -czf "${OUT_TAR}" -C "${ARTIFACTS_ROOT}" "${OUT_BASENAME}"

echo
echo "Done."
echo "Bundle path:"
echo "  ${OUT_TAR}"
echo
echo "Copy this archive to the target Mac, extract it, then follow README-import.md."
